# Font settings
# font_family      Maple Mono NF
font_size        12.0

# Pywal colors
include ~/.cache/wal/colors-kitty.conf


# Font Settings
# font_family      Maple Mono NF CN
# bold_font        Maple Mono NF CN Bold
# italic_font      Maple Mono NF CN Italic
# bold_italic_font Maple Mono NF CN Bold Italic


# Helpful for Maple Mono's specific ligatures
disable_ligatures never


# BEGIN_KITTY_FONTS
font_family      Maple Mono NF
bold_font        auto
italic_font      Maple Mono NF Italic
bold_italic_font auto
# END_KITTY_FONTS

# Fix: Added U+ to every hex code
symbol_map U+f5d7,U+e289,U+f1b0,U+db80-U+dbff Maple Mono NF CN

confirm_os_window_close 0

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
